---
name: Build Docs
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free space in hosted agent
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: apt-get install -y pandoc
          docs-folder: docs/
      - name: Commit documentation changes
        run: >
          git clone https://${{ secrets.PAT
          }}@github.com/Rishit-dagli/3d-transforms.git --branch gh-pages
          --single-branch gh-pages

          cp -r docs/build/html/* gh-pages/

          cd gh-pages

          touch .nojekyll

          git config --local user.email "action@github.com"

          git config --local user.name "GitHub Action"

          git add .

          git commit -m "Update documentation" -a || true

          # The above command will fail if no changes were present, so we ignore

          # that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: apt-get --allow-releaseinfo-change update -y && apt-get
            install -y latexmk texlive-latex-recommended texlive-latex-extra
            texlive-fonts-recommended imagemagick
          build-command: make latexpdf
          docs-folder: docs/
      # Save artifacts only for releases
      # - uses: actions/upload-artifact@v2
      #   if: contains(github.event.head_commit.message, 'save artifact')
      #   with:
      #     name: Documentation
      #     path: docs/build/latex/tensorflow3d-transforms.pdf
